[package]
name = "connect-wallet"
version = "0.1.0"
edition = "2021"
authors = ["Russell Wong"]

[dependencies]
dioxus = { version = "0.2.4", features = ["web", "router", "fermi"] }
log = "0.4.17"
wasm-logger = "0.2.0"
web3-anywhere = { path = "../../" }
